[package]
name = "abrelo"
version = "0.1.0"
description = "Regalos digitales interactivos que se descubren"
authors = ["Ghoztz"]
edition = "2021"

[lib]
name = "abrelo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
